# Generated by Django 4.2 on 2024-09-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PK',
            field=models.TextField(blank=True),
        ),
    ]
