# Generated by Django 4.2 on 2024-09-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='PK',
            new_name='PR',
        ),
    ]
